# Generated by Django 5.2.1 on 2025-06-01 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('logo', models.FileField(null=True, upload_to='images/manufacturers/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.FileField(upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturer'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField()),
                ('contact_email', models.CharField(null=True)),
                ('contact_phone', models.CharField(null=True)),
                ('message', models.TextField(null=True)),
                ('company', models.CharField(null=True)),
                ('inn', models.CharField(null=True)),
                ('order_type', models.CharField(choices=[('order', 'Заказ'), ('lising', 'Лизинг'), ('delivery', 'Доставка')])),
                ('order_status', models.CharField(choices=[('closed', 'Закрыт'), ('opened', 'Открыт')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory'),
        ),
    ]
